server:
  port: 8082
spring:
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: spring-boot-hazelcast
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hazel-cast-demo
    username: root